# Generated by Django 5.0.14 on 2026-03-13 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dot_spacing", models.IntegerField(default=10)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("classic", "Classic"),
                            ("diamond", "Diamond"),
                            ("line", "Line"),
                        ],
                        default="classic",
                        max_length=20,
                    ),
                ),
                ("max_uploads", models.IntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
